//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyUserMapping
    {
        public int RecordId { get; set; }
        public int AgencyId { get; set; }
        public int UserId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual VUsers VUsers { get; set; }
    }
}
