//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMovingItem
    {
        public int RecordId { get; set; }
        public int ItemId { get; set; }
        public int previousUserId { get; set; }
        public int currentUserId { get; set; }
        public int currentStatusId { get; set; }
        public System.DateTime curretnDateTime { get; set; }
        public string notes { get; set; }
    
        public virtual IStatus IStatus { get; set; }
        public virtual VUsers VUsers { get; set; }
        public virtual Items Items { get; set; }
        public virtual VUsers VUsers1 { get; set; }
    }
}
