//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryManagmentSystemEntities : DbContext
    {
        public InventoryManagmentSystemEntities()
            : base("name=InventoryManagmentSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agency> Agency { get; set; }
        public virtual DbSet<AgencyUserMapping> AgencyUserMapping { get; set; }
        public virtual DbSet<IBrand> IBrand { get; set; }
        public virtual DbSet<IMovingItem> IMovingItem { get; set; }
        public virtual DbSet<IReturnItem> IReturnItem { get; set; }
        public virtual DbSet<IStatus> IStatus { get; set; }
        public virtual DbSet<ItemHistory> ItemHistory { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<IType> IType { get; set; }
        public virtual DbSet<LLocation> LLocation { get; set; }
        public virtual DbSet<StoreItems> StoreItems { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<UsersItems> UsersItems { get; set; }
        public virtual DbSet<VUsers> VUsers { get; set; }
        public virtual DbSet<ReportingSystem> ReportingSystem { get; set; }
    }
}
