//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.IMovingItem = new HashSet<IMovingItem>();
            this.IReturnItem = new HashSet<IReturnItem>();
            this.ItemHistory = new HashSet<ItemHistory>();
            this.StoreItems = new HashSet<StoreItems>();
            this.UsersItems = new HashSet<UsersItems>();
            this.ReportingSystem = new HashSet<ReportingSystem>();
        }
    
        public int ItemId { get; set; }
        public string ISerialNum { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemBrandId { get; set; }
        public int IStatusID { get; set; }
        [Required]
        public Nullable<int> IStore { get; set; }
    
        public virtual IBrand IBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMovingItem> IMovingItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IReturnItem> IReturnItem { get; set; }
        public virtual IStatus IStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemHistory> ItemHistory { get; set; }
        public virtual IType IType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreItems> StoreItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersItems> UsersItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportingSystem> ReportingSystem { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
