//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportingSystem
    {
        public int RecordId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual IBrand IBrand { get; set; }
        public virtual IStatus IStatus { get; set; }
        public virtual Items Items { get; set; }
        public virtual IType IType { get; set; }
        public virtual LLocation LLocation { get; set; }
        public virtual Stores Stores { get; set; }
        public virtual VUsers VUsers { get; set; }
    }
}
