//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreItems
    {
        public int RecordId { get; set; }
        public int StoreId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
