//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryMnamgmentSystemV5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersItems
    {
        public int RecordId { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public System.DateTime currentDateTime { get; set; }
        public Nullable<int> CurrentStatusId { get; set; }
    
        public virtual IStatus IStatus { get; set; }
        public virtual Items Items { get; set; }
        public virtual VUsers VUsers { get; set; }
    }
}
